[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.x"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.x"

[[constraint]]
  branch = "master"
  name = "github.com/d5/go-httputil"
